[package]
name = "ex015-concate-words-by-letter"
version = "0.1.0"
authors = ["The25thBam <The25thBam@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"